### ISSUE TITLE
Version 2.0.0 introduces weird backgrounds in code blocks

### ISSUE THREAD

**Issue by paulkoegel** [gaearon/gitbook-plugin-prism#11]
I just tried building new offline versions of the redux docs (https://github.com/paulkogel/redux-offline-docs) and noticed the following problem with version 2.0.0 (/cc @robmcguinness):

Screenshot from the PDF (no text highlighting by the user!):
---

<img width="1024" alt="screen shot 2016-11-19 at 22 48 59" src="https://cloud.githubusercontent.com/assets/513255/20458623/81dce2a0-aeaa-11e6-9931-ae6696e53c41.png">

---

There was no mouse interaction but the text in the code block looks kind of highlighted.
After reverting to gitbook-plugin-prism 1.1.0 the backgrounds disappeared.

here are my installed packages:
Node version: 7.0.0
Gitbook CLI version: 2.3.0
GitBook version: 3.2.1

Gitbook plugins:
gitbook-plugin-algolia@1.0.7
gitbook-plugin-anchorjs@1.1.1
gitbook-plugin-edit-link@2.0.2
gitbook-plugin-github@2.0.0
gitbook-plugin-prism@2.0.0

**Comment by robmcguinness** [comment]
Must this is related to the code I added to add the appropriate classes to the `<pre>`.

**Comment by robmcguinness** [comment]
I was able to duplicate the PDF issue using https://github.com/robmcguinness/gitbook-prism-example.  The solarized light theme also had same issue.

![image](https://cloud.githubusercontent.com/assets/281070/20459189/e5bfcfe0-ae86-11e6-96d8-79b64c330b76.png)

Investigating 🤔

**Comment by robmcguinness** [comment]
Each Prism theme has the following CSS:

```css
pre[class*="language-"]::selection, pre[class*="language-"] ::selection,
code[class*="language-"]::selection, code[class*="language-"] ::selection {
	text-shadow: none;
	background: #b3d4fc;
}
```

Somehow the `::selection` selector is being applied to the PDF which is causing the text to have a background.

![image](https://cloud.githubusercontent.com/assets/281070/20497843/bed24a70-aff8-11e6-925f-96eb04f72f6d.png)

Setting the background to none for each `::selection` resolves the background issue on the text.

```css
pre[class*="language-"]::selection, pre[class*="language-"] ::selection,
code[class*="language-"]::selection, code[class*="language-"] ::selection {
	text-shadow: none;
	background: none;
}
```

![image](https://cloud.githubusercontent.com/assets/281070/20498010/755e4730-aff9-11e6-84af-5e985a89d847.png)

I'm not well versed on how Calibre converts CSS for PDFs.  Maybe the prism plugin should just create a custom PDF css that removes the background color on the `::selection` selector Investigating 💭

**Comment by robmcguinness** [comment]
Same issue for Solarized Light theme:

![image](https://cloud.githubusercontent.com/assets/281070/20498380/fed766b2-affa-11e6-9bd5-ffd407ae3f6d.png)

Setting the `::selection` background to none does not resolve the issue completely 🔥 

![image](https://cloud.githubusercontent.com/assets/281070/20498443/379c7e06-affb-11e6-9a3c-a4f5a318d41e.png)

**Comment by robmcguinness** [comment]
It appears a style in `pdf.css` is causing the Solarized Theme to not working properly inside a PDF.  Setting the background color to `none` in the selector below fixes the issue:

```css
.page .section code {
    padding: .2em;
    margin: 0;
    font-size: .85em;
    background-color: none;
}
```

![image](https://cloud.githubusercontent.com/assets/281070/20499445/86a2c222-afff-11e6-8d43-32ade75a31dd.png)
